### PR TITLE
Added copying README.md from content/ to output/

### PR DESCRIPTION
**Pull request by juskuz**
It should be working.

### CODE REVIEW

**Review by aniawsz — CHANGES_REQUESTED** [review]
Looks like some old commits got included in this PR. Please rebase the changes on the current master first.

Apart from that, LGTM! :)

**Review by aniawsz — APPROVED** [review]

**Comment by aniawsz** [comment]
Ok, accepting the changes since rebasing can be done automatically with the merge button :)

**Comment by magul** [comment]
@aniawsz i believe we don’t have so much people here to go with more than one approval, so if it looks fine to you, just use green button :)

BTW what’s the plan for a weekend?

**Comment by aniawsz** [comment]
Tried to rebase, but there are conflicts. Can you resolve @juskuz ?

**Comment by juskuz** [comment]
Today evening and tomorrow morning I'll have time to see and resolve this problem. ;)

**Comment by juskuz** [comment]
@aniawsz 
I found what was wrong and I fixed it.

**Comment by juskuz** [comment]
But I made new branch and PR.

**Pull request closed without merging**
